name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Setup Node ğŸ˜»
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install ğŸ“º
        run: npm ci
      - name: Lint ğŸ‘–
        run: npm run lint
      - name: Typecheck ğŸ¹
        run: npm run types
      - name: Unit Tests ğŸ“
        run: npm test
      - name: Accessibility Tests ğŸ¤Ÿ
        run: npm run storybook:axe
      - name: Build ğŸš§
        run: npm run build
