name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs â›”
        uses: styfle/cancel-workflow-action@0.11.0
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Setup Node ğŸ˜»
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install ğŸ“º
        run: npm ci
      - name: Lint ğŸ‘–
        run: npm run lint
      - name: Typecheck ğŸ¹
        run: npm run types
      - name: Unit Tests ğŸ“
        run: npm test
      - name: Accessibility Tests ğŸ¤Ÿ
        run: npm run storybook:axe
      - name: Build ğŸš§
        run: npm run build

      # # To use Chromatic for [visual regression testing](https://czi.atlassian.net/wiki/x/SYCFiw):
      # # 1. Un-comment this entire block.
      # # 2. Create a new project in Chromatic per https://www.chromatic.com/docs/setup#sign-up.
      # # 3. Add its unique project token to GitHub as a `CHROMATIC_PROJECT_TOKEN` secret.
      # - name: Publish to Chromatic
      #   uses: chromaui/action@v1
      #   with:
      #     autoAcceptChanges: main
      #     exitOnceUploaded: true
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #     onlyChanged: true
